baseURL = "https://garethr.dev/"
languageCode = "en-gb"
title = "garethr.dev"
theme = "hyde"

pygmentsCodefences = true
pygmentsStyle = "solarized-dark"

[permalinks]
  posts = "/:year/:month/:title/"
